### ISSUE TITLE
Change the twitter icon in the feeback also

### ISSUE THREAD

**Issue by jennifereunice** [apu52/Travel_Website#1077]
![image](https://github.com/user-attachments/assets/cbc56023-08c1-438d-8d8c-3e67f3a44528)

**Comment by apu52** [comment]
@jennifereunice there is no proper description of the issue .I can not understand the issue. please use the issue templates (which are already present in the repo) to submit your issue so that it will be more clear & understandable. Sorry to close this issue. But u can still make new issues with proper format
