### ISSUE TITLE
button to return to home from feedback

### ISSUE THREAD

**Issue by jennifereunice** [apu52/Travel_Website#1078]
![image](https://github.com/user-attachments/assets/272d1375-64db-4219-a1bb-29ee5e14f875)

**Comment by apu52** [comment]
@jennifereunice there is no proper description of the issue .I can not understand the issue. please use the issue templates (which are already present in the repo) to submit your issue so that it will be more clear & understandable. Sorry to close this issue. But u can still make new issues with proper format
