### ISSUE TITLE
Check-in and Check-out issue

### ISSUE THREAD

**Issue by Kiran511-git** [apu52/Travel_Website#1425]
There is a issue in book tour page.When we want to select check-in date and check-out data we need to click the calender icon.We just want to update it.When we click on the field it needs to take input value rather than clicking the calender button.

**Comment by apu52** [comment]
@Kiran511-git Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
