### ISSUE TITLE
Update Color Palette and Template for Improved Aesthetic

### ISSUE THREAD

**Issue by aparna-44** [apu52/Travel_Website#1433]
The current travel website functions well, but its visual appeal can be enhanced with a new color palette and a refreshed template. These changes will modernize the look and feel of the site, making it more inviting and aligned with current design trends.
It will enhances the website’s visual appeal, creating a more welcoming experience for users,
makes the website look more professional and modern, which can attract more visitors, and improves the usability and overall user interface without changing the core functionality.
@apu52 plz assign me this issue,i really want to work on it.

**Comment by apu52** [comment]
@aparna-44 
Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
