### ISSUE TITLE
UI Improvements: Navbar Alignment, Button Styling, Image Loading, and Overall Layout

### ISSUE THREAD

**Issue by Kavish-Paraswar** [apu52/Travel_Website#1434]
The dark mode button is misaligned and extends beyond the screen, affecting the visual appeal of the navbar.
![image](https://github.com/user-attachments/assets/76da10c1-5aad-43cf-a5f4-fddbe6bbf015)

After hovering, the red underline extends beyond the button, creating an undesirable UI experience.
![image](https://github.com/user-attachments/assets/829b505f-6ea0-4c95-be11-fd51e2963bf1)

One of the images is not loading correctly, impacting the page's presentation.
![image](https://github.com/user-attachments/assets/ceaedea4-8f40-4a5d-b644-cf21f1811905)

The alignment and arrangement of UI elements are not professional, leading to a poor user experience. I would like to work on fixing these issues and improving the overall design.
![image](https://github.com/user-attachments/assets/f16d2e90-7e48-40b8-bf7e-16e8ad10875d)

**Comment by apu52** [comment]
![image](https://github.com/user-attachments/assets/4d297c0f-4811-4751-9700-01880673348c)


only this issue is still lies on the website . So try to raise a new issue on this problem only .As the other problem issues has already been assigned to other contributors .
But I can't assign u this issue as U haven't followed the issues templates

@Kavish-Paraswar 
Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
