### ISSUE TITLE
Improvement in accessing files

### ISSUE THREAD

**Issue by VIROHuman** [apu52/Travel_Website#1446]
The project has an unorganised space for images and other files.
![Screenshot 2024-10-06 231733](https://github.com/user-attachments/assets/aba49a27-3d78-4e43-892d-a4051a1e9159)
I would like to work on this issue. Please assign me the roles to it.
I have read the contribution guidelines.
(GSSoC^24 contributor)

**Comment by apu52** [comment]
@VIROHuman Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
