### ISSUE TITLE
Improve contact page with good UI for text area 

### ISSUE THREAD

**Issue by rahulbamnuya** [apu52/Travel_Website#1450]
I want to improve a contact page by make good Ui for it and also want to  improve text area 
[
![Screenshot (114)](https://github.com/user-attachments/assets/f33b4bb6-d4c8-4ad8-af91-4455779c113b)
](url)
 I have read the Contributing Guidelines
 I'm a GSSOC'24 contributor
 I'm a VSOC'24 contributor
 I have starred the repository
@apu52 
Can you assign this issue to me under gssoc and hactoberfest

**Comment by apu52** [comment]
@rahulbamnuya Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
