### ISSUE TITLE
Accessible travel contact page problem

### ISSUE THREAD

**Issue by Shirisha-16** [apu52/Travel_Website#1454]
The contact page get submitted without entering the required details.
![Screenshot 2024-10-07 120409](https://github.com/user-attachments/assets/7f98256e-7b74-42b3-9f5b-9e8177d8cc9d)
 
I want to work on this issue . Please assign me this work with the labels gssoc-ext ,hacktoberfest-accepted and level according to this issue

**Comment by apu52** [comment]
@Shirisha-16 Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
