### ISSUE TITLE
Add an overlay video to the local events and festivals

### ISSUE THREAD

**Issue by ThunderShadows** [apu52/Travel_Website#1487]
The images for the enthusiastic festivals section looks static and not responsive enough.

@apu52 

I shall add an overlay video for the local events section as well as animate the texts for better responsiveness and interactivity for the users.

**Comment by apu52** [comment]
@ThunderShadows Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .

**Comment by ThunderShadows** [comment]
> @ThunderShadows Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info. This issue is good just try to raise a new issue on same topic using the issue templates already given Sorry to close this issue for now .

Ok Sir. Thank you for your time!
