### ISSUE TITLE
There is some issue with packages page

### ISSUE THREAD

**Issue by Mehak-Parveen** [apu52/Travel_Website#1489]
the contents in title are not in-line.
https://www.google.com/url?q=https://github.com/Komal15agarwal/SI-2024-Cubesat-KA&sa=D&source=editors&ust=1728043281056902&usg=AOvVaw0QuyTFqOPw_3N0fUiUaIIX

Can you assign me the  issue i would like to work on it.
![Screenshot 2024-10-11 074858](https://github.com/user-attachments/assets/4b120cdf-29d0-4c86-a4d4-b79caff09021)

**Comment by Mehak-Parveen** [comment]
@sanjay-kv 
the contents in title are not in-line.
https://www.google.com/url?q=https://github.com/Komal15agarwal/SI-2024-Cubesat-KA&sa=D&source=editors&ust=1728043281056902&usg=AOvVaw0QuyTFqOPw_3N0fUiUaIIX

Can you assign me the issue i would like to work on it.
![Screenshot 2024-10-11 074858](https://github.com/user-attachments/assets/0e2a3723-d98c-4c68-917c-2ed7e1ba7033)

**Comment by apu52** [comment]
@Mehak-Parveen  Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
this issue is already present in the repo previously & already been assigned to another contributor
Sorry to close this issue for now . but u can still make new issues on which u want to work on
