### ISSUE TITLE
Improve the hover effect and keep the color consistent according to the theme of this website.

### ISSUE THREAD

**Issue by vaibhavrajharsh** [apu52/Travel_Website#1515]
Here you can see that the Hover Effect is not looking good and the color of the shadow behind those buttons are not matching with the theme of this website.
![Screenshot 2024-10-13 214244](https://github.com/user-attachments/assets/2b8c1c76-da85-4ce4-acc8-6730e0e0e2eb)

**Comment by vaibhavrajharsh** [comment]
@sanjay-kv project admin not responding

**Comment by apu52** [comment]
@vaibhavrajharsh Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
 this issue is already present in the repo previously & already been assigned to another contributor . sorry to close this issue . but u can still make new issues on which u want to work on
Sorry to close this issue for now .
