### ISSUE TITLE
Problem in the Style of Hover effect in Header

### ISSUE THREAD

**Issue by vaibhavrajharsh** [apu52/Travel_Website#1516]
here you can see that the hover effect is not looking good. Those underlines are bigger than those buttons.
and color selection is not good
![Screenshot 2024-10-13 215317](https://github.com/user-attachments/assets/73ec33e3-871c-4738-8513-0e3ac854736f)

**Comment by abhagangwar712** [comment]
Hello @apu52, would you please assign this task to me.

**Comment by vaibhavrajharsh** [comment]
@apu52 please assign me this issue... 
I can fix that.

**Comment by vaibhavrajharsh** [comment]
@sanjay-kv they are not responding

**Comment by sanjay-kv** [comment]
@vaibhavrajharsh you can see 200 issues, and last PR merged was 4 days ago, give them some time and focus on other active repos.

**Comment by apu52** [comment]
@vaibhavrajharsh  
Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
