### ISSUE TITLE
FEATURE: ADD SKELETON LAODING TO THE PAGES

### ISSUE THREAD

**Issue by shubhagarwal1** [apu52/Travel_Website#1570]
HEY @apu52 i am open to implement the feature on the pages you want me to

**Comment by apu52** [comment]
@shubhagarwal1 Please try to follow the issue templates which are already provided in the repo to raise your issue , otherwise it will be difficult for me/mentors to assign u the issue without much info.
This issue is good just try to raise a new issue on same topic using the issue templates already given 
Sorry to close this issue for now .
