### ISSUE TITLE
[Bug]: View button lead to blank page

### ISSUE THREAD

**Issue by kritiup** [apu52/Travel_Website#1641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Add ScreenShots/Videos

https://github.com/user-attachments/assets/cb0cd59c-b194-454c-9283-ea61f3124682

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a  IEEE-IGDTUW Open Source Week 2024 contributor
- [X] I have starred the repository

**Comment by apu52** [comment]
@kritiup what u want to do with the view page ??
As the View page needs the Live google map API , the code is still present in the repo , but the backend is not connected till now , 
So what u want to do in this issue like which features u want to add or fix any bugs??

**Comment by neeraj10122004** [comment]
As Live google map API is not free instead of using it for time being and look of website i suggest using Leaflet.js which provides basic map we can statically add the locations of the places in this Leaflet.js and i am going to make a pull request for this issue please merge this into main branch
![image](https://github.com/user-attachments/assets/5a4c6060-9d0a-4781-ae7d-1f72799a7225)
this will be the output after adding this new pull request

**Comment by neeraj10122004** [comment]
please merge this pull request or suggest any changes that should i make so that my request is merged @apu52
