### ISSUE TITLE
[Bug]:  packages page Navbar UI fixed 

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [apu52/Travel_Website#1648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in your website at packages page the Navbar UI should be fixed its alignment is not good they should be more space between nav items same with buttons 

### Expected behavior

alignment fix of navbar

### Add ScreenShots/Videos

![WhatsApp Image 2024-11-25 at 23 35 54_11f9e639](https://github.com/user-attachments/assets/56f90822-ac30-4211-98e4-cd50d1a15416)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a  IEEE-IGDTUW Open Source Week 2024 contributor
- [X] I have starred the repository

**Comment by neeraj10122004** [comment]
@apu52 please assign this issue to me

**Comment by apu52** [comment]
@biswajit-sarkar-007 Actually i want to inform u one thing , that the contribution period of kwoc will start from 5 th dec , so any contributions before that timeline will not count towards KWOC , so please try to start contributing after 5th DEC .

& regarding this issues which u have raised prior , don't worry about it , i will review & assign u this issues after the contribution period starts

& please don't raise more than 2 issues at a time ,otherwise it violates the rules of the repo , so i have to close the other issues

**Comment by apu52** [comment]
@biswajit-sarkar-007 i have assigned u 2 issues . So try to make 2 different PR while submitting the issues

**Comment by apu52** [comment]
@neeraj10122004 this issue is already assigned . try to make new issues on which u want to work on .
