### ISSUE TITLE
BUG : CHATBOT 

### ISSUE THREAD

**Issue by apu52** [apu52/Travel_Website#174]
**Describe the bug**

Hello All,
There is a Chatbot in the webpage & the chatbot is not working upto the mark.

**Expected behavior**

I just want the chatbot functionable . Make the chatbot functionable even can make it more functionable by adding more elements

**Screenshots (Mandatory)**

![image](https://github.com/apu52/Travel_Website/assets/114172928/85968259-ddad-4580-bd16-891554d45f68)

**Additional Context (Mandatory )**

### Those whoever comment first with JWOC mentioned in it  I will assign it to HER/HIM

***Are you contributing under any open-source program ?***

JWOC'24

**Comment by Anushkabh** [comment]
i would like to work under jwoc @apu52 kindly assign

**Comment by apu52** [comment]
@Anushkabh You are assigned. You have 2-3 days to submit your PR.
Happy coding!!!!!!!!!

**Comment by dPacc** [comment]
Hey guys :) 

I'm the maker of Conferbot, I see that you have run out of your chat quota for the month. 

Since you guys are students, I'll be happy to increase your chat quota to 1500 chats/month for free for 2 months.

A little tip to help you manage better: Try turning off the **Bot Auto Open** feature. You'll find it under **Customizations -> Advanced**. This should help prevent using up your chat quota too quickly.

If you'd like to take up this offer, just let me know.

Good luck!

**Comment by apu52** [comment]
@dPacc Thank you for your concern & the tips  . As now for somedays this repo is under a open source programme JWOC , & this issue is already assigned so , @Anushkabh I think you can take the tips mentioned above

**Comment by Anushkabh** [comment]
@apu52 yes I have taken into account the tips mentioned .. working on that will push it by eod

**Comment by Anushkabh** [comment]
@apu52 kindly review the pr #231  and merge if satisfied.
