### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by sharmi4590** [apu52/Travel_Website#388]
Hey @apu52 
**Describe the bug**
The web pages are not at all responsive.

**Expected behavior**
We can do it by adding some CSS media queries and bootstrap, because it is important to make it available in all the devices, not only to larger-width devices.

**Screenshots (Mandatory)**
![Screenshot (367)](https://github.com/apu52/Travel_Website/assets/102676949/c52536f9-21b1-45eb-b70b-fd90c6d397cf)

***Are you contributing under any open-source program ?***
I am only contributing in GSSoC'24

**Comment by 39palakved** [comment]
I would like to work on this issue . Please assign this task to me

**Comment by Its-your-rj** [comment]
Subject: Asking to contribute in order to Enhance Responsiveness with CSS Media Queries and Bootstrap


I hope this message finds you well.  I'm excited about the opportunity to contribute to its development.

I've noticed that ensuring responsiveness across various devices is crucial for user experience. I'd like to propose adding CSS media queries and integrating Bootstrap to achieve this goal effectively.

I have experience working with CSS media queries and Bootstrap's responsive design components, and I believe implementing them in this could greatly enhance its accessibility and usability across all devices.

Would it be possible for me to contribute to this aspect of the project? I'm eager to learn any specific guidelines or standards the project follows and would appreciate any guidance you can provide.

Looking forward to the opportunity to collaborate.

Best regards,
Raj Mehta

**Comment by apu52** [comment]
#328  is already present there. So thanks for raising this issue But Sorry I can't assign you this issue right now.

**Comment by apu52** [comment]
@Its-your-rj @39palakved This
