### ISSUE TITLE
Change the AboutUs to About us in Navigation bar

### ISSUE THREAD

**Issue by Bindusree1515** [apu52/Travel_Website#416]
**Describe the bug**

- The navigation bar on the website currently displays "AboutUs," which is grammatically incorrect. It should be displayed as "About Us" with a space between the words for proper grammar and readability.

**Expected behavior**

- The navigation link should display as "About Us" for correct grammar and clarity.

**Screenshots (Mandatory)**

- Our Website :

![image](https://github.com/apu52/Travel_Website/assets/91887086/6cc1e57a-5ac7-464a-bb0f-4827795977aa)
- After correction : (its just a sample of other website)

![image](https://github.com/apu52/Travel_Website/assets/91887086/c1da93cb-35bd-4df7-9b64-879c70b367b3)

**Additional Context (Mandatory )**
- This change is important to ensure the professionalism and readability of the website's navigation. Proper grammar enhances user experience and contributes to a better overall impression.

***Are you contributing under any open-source program ?***
- Yes, GSSOC'24.

@apu52 please assign me this issue , resolving it would increase readability and professionalism.

**Comment by apu52** [comment]
@Bindusree1515 You are assigned.

**Comment by numitasahu** [comment]
**Describe the bug**

-  The image of the home page is currently a fixed image  and if there is a random traveling image which changes on every refresh then it will give a better positive impact and it will also look good to see together
- and also need to apply some transitions 

**Expected behavior**

- random traveling image  and transitions  will give a better positive impact ,attractiveness and it will also look good to see together 

**Screenshots (Mandatory)**

- Our Website :
![teavel2](https://github.com/apu52/Travel_Website/assets/148805208/53829d66-5e18-41fe-9eb4-706553a77055)

- After correction : (its just a sample of other website)
 ![travel bug](https://github.com/apu52/Travel_Website/assets/148805208/0351bdcb-af5d-4f21-8f8e-8040abc0a04c)

**Are you contributing under any open-source program ?**

Yes, GSSOC'24.
@apu52 please assign me this issue , resolving it would increase attractiveness and look good.

**Comment by RedWing0021** [comment]
Please assign this to me!!

**Comment by apu52** [comment]
@numitasahu your issue is really good. but just want to suggest u to raise a complete new issue to get assigned .Don't comment on other's issues . Waiting for your new Issue eagerly
